/**
 * Generate openapi.yaml from NestJS Swagger metadata without starting HTTP.
 *
 * Usage: pnpm openapi:generate
 *
 * Boots AppModule with Prisma overridden (no Mongo) and workers disabled.
 * Redis is still configured for BullMQ queue registration but no jobs run.
 */

process.env.NODE_ENV = 'test';
process.env.DISABLE_WORKERS = 'true';
process.env.THROTTLE_STORAGE = 'memory';
process.env.OTEL_SDK_DISABLED = 'true';
process.env.SWAGGER_ENABLED = 'false';
process.env.DATABASE_URL =
  process.env.DATABASE_URL ??
  'mongodb://127.0.0.1:27017/hypertron_openapi_gen?directConnection=true';
process.env.REDIS_URL = process.env.REDIS_URL ?? 'redis://127.0.0.1:6379';
process.env.AUTH_SECRET =
  process.env.AUTH_SECRET ?? 'openapi-gen-auth-secret-32chars!!';
process.env.INTERNAL_SERVICE_TOKEN =
  process.env.INTERNAL_SERVICE_TOKEN ?? 'openapi-gen-internal-token-32!!';
process.env.WEBHOOK_SECRET_ENCRYPTION_KEY =
  process.env.WEBHOOK_SECRET_ENCRYPTION_KEY ?? '0'.repeat(64);

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { VersioningType } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { SwaggerModule } from '@nestjs/swagger';
import * as yaml from 'js-yaml';

import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/infrastructure/prisma/prisma.service';
import { buildOpenApiConfig } from '../src/common/openapi/openapi.config';

async function main(): Promise<void> {
  const moduleRef = await Test.createTestingModule({
    imports: [AppModule],
  })
    .overrideProvider(PrismaService)
    .useValue({
      $connect: async () => undefined,
      $disconnect: async () => undefined,
      $on: () => undefined,
      $transaction: async (fn: (tx: unknown) => Promise<unknown>) => fn({}),
      onModuleInit: async () => undefined,
      onModuleDestroy: async () => undefined,
    })
    .compile();

  const app = moduleRef.createNestApplication();
  app.enableVersioning({ type: VersioningType.URI });
  await app.init();

  const document = SwaggerModule.createDocument(app, buildOpenApiConfig(), {
    operationIdFactory: (controllerKey: string, methodKey: string) =>
      `${controllerKey}_${methodKey}`,
  });

  const outPath = join(__dirname, '..', 'openapi.yaml');
  const header = [
    '# Generated by `pnpm openapi:generate` — do not edit by hand.',
    '# Source of truth: NestJS controllers + DTOs (Payments_API_v1_Schema.md is the contract).',
    '',
  ].join('\n');

  writeFileSync(
    outPath,
    header +
      yaml.dump(document, {
        noRefs: true,
        lineWidth: 120,
        sortKeys: false,
      }),
    'utf8',
  );

  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath} (${Object.keys(document.paths ?? {}).length} paths)`);

  await app.close();
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
